<br/><br/>
<div id="view-content">
    <h2>Current Bugs</h2>
    <?php
    echo $this->listTools;
    ?>
    <?php
    echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination-control.phtml');
    ?>
    <table class='spreadsheet' cellspacing='0'>
        <tr>
            <th>&nbsp;</th>
            <th>Datum</th>
            <th>Prioriteit</th>
            <th>Status</th>
            <th>URL</th>
            <th>Auteur</th>
            <th>Beschrijving</th>
        </tr>
        <?php echo $this->partialLoop('bug/table-row.phtml', $this->paginator); ?>
    </table>
</div>