<?php
/**
 * @package     ZF_CMS_JOR
 *
 * @author      Jor Sanders
 *
 * the default layout
 */
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();
$this->layout()->nav = $this->action('render', 'menu', null, array('menu' => $this->mainMenuId));
$this->layout()->adminMenu = $this->action(
    'render', 'menu', null, array('menu' => $this->adminMenuId)
);
$this->layout()->userForm = $this->action('index', 'user');
?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <?php
    $this->loadSkin($this->skin);
    echo $this->headTitle();
    echo $this->headScript();
    echo $this->headLink();
    ?>
</head>
<body>
<div id="pageWrapper">
    <div id="header">
        <h1>Zend Framework CMS</h1>
    </div>
    <div id="nav">
        <?php
        echo $this->layout()->nav;
        ?>&nbsp;
    </div>
    <div id="sidebar">
        <div id='searchForm'>
            <h2>Search Site</h2>
            <?php
            $searchForm = new Form_Search();
            $searchForm->setAction('/search');
            echo $searchForm;
            ?>
            <br/>
        </div>
        <div id="feeds">
            <h2>Feeds</h2>
            <p><a href='/feed/rss'>Click Here</a> to subscribe to our RSS feed.</p>
        </div>
        <div id="subNav">
            <?php
            echo $this->layout()->subNav;
            ?>&nbsp;
        </div>
        <div id="adminMenu">
            <?php
            echo $this->layout()->adminMenu;
            ?>&nbsp;
        </div>
        <div id="userForm">
            <?php
            echo $this->layout()->userForm;
            ?>&nbsp;
        </div>
    </div>
    <div id="main">
        <?php echo $this->layout()->content ?>&nbsp;
    </div>
    <div id="footer">
        <p><em>ZF_CMS Jor</</p>
    </div>
</div>
</body>
</html>